version: '3.8'
services:
  csrgen:
    build: .
    ports:
      - "443:443"
    volumes:
      - ./certs:/certs
    environment:
      - ENV=production
      - PORT=443
      - CERT_FILE=/certs/server.crt
      - KEY_FILE=/certs/server.key
    restart: always
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"