name: 'Generate Release Notes'
description: 'Generates release notes from commit messages'
inputs:
  tag:
    description: 'Release tag'
    required: true
runs:
  using: 'composite'
  steps:
    - run: |
        if git describe --tags --abbrev=0 HEAD^ 2>/dev/null; then
          previous_tag=$(git describe --tags --abbrev=0 HEAD^)
          changes=$(git log --pretty=format:'- %s' $previous_tag..HEAD)
        else
          changes=$(git log --pretty=format:'- %s' HEAD)
        fi
        gh release edit ${{ inputs.tag }} --notes "$changes"
      shell: bash
      env:
        GH_TOKEN: ${{ github.token }}