name: Build csrgen

on:
 release:
   types: [created]

jobs:
 build:
   runs-on: ubuntu-latest
   steps:
   - uses: actions/checkout@v4

   - name: Login to GitHub Container Registry
     uses: docker/login-action@v3
     with:
       registry: ghcr.io
       username: ${{ github.actor }}
       password: ${{ secrets.GITHUB_TOKEN }}

   - name: Build and Push
     run: |
       IMAGE_NAME=ghcr.io/${{ github.repository_owner }}/${{ github.event.repository.name }}
       VERSION=${{ github.event.release.tag_name }}
       
       docker build -f Containerfile -t $IMAGE_NAME:$VERSION .
       docker tag $IMAGE_NAME:$VERSION $IMAGE_NAME:latest
       
       docker push $IMAGE_NAME:$VERSION
       docker push $IMAGE_NAME:latest
