name: Build csrgen

on:
 workflow_dispatch:
 release:
   types: [created]

jobs:
 build:
   runs-on: ubuntu-latest
   steps:
   - uses: ./.github/actions/checkout
   - uses: ./.github/actions/docker-login

   - name: Build and Push
     run: |
       IMAGE_NAME=ghcr.io/${{ github.repository_owner }}/${{ github.event.repository.name }}
       VERSION=${{ github.event.release.tag_name }}
       
       docker build -f Containerfile -t $IMAGE_NAME:$VERSION .
       docker tag $IMAGE_NAME:$VERSION $IMAGE_NAME:latest
       
       docker push $IMAGE_NAME:$VERSION
       docker push $IMAGE_NAME:latest
